package is.ejb.bl.acra;

public class AcraSettingsSecure {
	private int ADB_ENABLED;
	private int ALLOW_MOCK_LOCATION;
	private int BLUETOOTH_ON;
	private int DATA_ROAMING;
	private String DEFAULT_INPUT_METHOD;
	private int DEVICE_PROVISIONED;
	private String ENABLED_INPUT_METHODS;
	private int INSTALL_NON_MARKET_APPS;
	private String LOCATION_PROVIDERS_ALLOWED;
	private int NETWORK_PREFERENCE;
	private int USB_MASS_STORAGE_ENABLED;
	private int WIFI_NETWORKS_AVAILABLE_NOTIFICATION_ON;
	private int WIFI_ON;
	public int getADB_ENABLED() {
		return ADB_ENABLED;
	}
	public void setADB_ENABLED(int aDB_ENABLED) {
		ADB_ENABLED = aDB_ENABLED;
	}
	public int getALLOW_MOCK_LOCATION() {
		return ALLOW_MOCK_LOCATION;
	}
	public void setALLOW_MOCK_LOCATION(int aLLOW_MOCK_LOCATION) {
		ALLOW_MOCK_LOCATION = aLLOW_MOCK_LOCATION;
	}
	public int getBLUETOOTH_ON() {
		return BLUETOOTH_ON;
	}
	public void setBLUETOOTH_ON(int bLUETOOTH_ON) {
		BLUETOOTH_ON = bLUETOOTH_ON;
	}
	public int getDATA_ROAMING() {
		return DATA_ROAMING;
	}
	public void setDATA_ROAMING(int dATA_ROAMING) {
		DATA_ROAMING = dATA_ROAMING;
	}
	public String getDEFAULT_INPUT_METHOD() {
		return DEFAULT_INPUT_METHOD;
	}
	public void setDEFAULT_INPUT_METHOD(String dEFAULT_INPUT_METHOD) {
		DEFAULT_INPUT_METHOD = dEFAULT_INPUT_METHOD;
	}
	public int getDEVICE_PROVISIONED() {
		return DEVICE_PROVISIONED;
	}
	public void setDEVICE_PROVISIONED(int dEVICE_PROVISIONED) {
		DEVICE_PROVISIONED = dEVICE_PROVISIONED;
	}
	public String getENABLED_INPUT_METHODS() {
		return ENABLED_INPUT_METHODS;
	}
	public void setENABLED_INPUT_METHODS(String eNABLED_INPUT_METHODS) {
		ENABLED_INPUT_METHODS = eNABLED_INPUT_METHODS;
	}
	public int getINSTALL_NON_MARKET_APPS() {
		return INSTALL_NON_MARKET_APPS;
	}
	public void setINSTALL_NON_MARKET_APPS(int iNSTALL_NON_MARKET_APPS) {
		INSTALL_NON_MARKET_APPS = iNSTALL_NON_MARKET_APPS;
	}
	public String getLOCATION_PROVIDERS_ALLOWED() {
		return LOCATION_PROVIDERS_ALLOWED;
	}
	public void setLOCATION_PROVIDERS_ALLOWED(String lOCATION_PROVIDERS_ALLOWED) {
		LOCATION_PROVIDERS_ALLOWED = lOCATION_PROVIDERS_ALLOWED;
	}
	public int getNETWORK_PREFERENCE() {
		return NETWORK_PREFERENCE;
	}
	public void setNETWORK_PREFERENCE(int nETWORK_PREFERENCE) {
		NETWORK_PREFERENCE = nETWORK_PREFERENCE;
	}
	public int getUSB_MASS_STORAGE_ENABLED() {
		return USB_MASS_STORAGE_ENABLED;
	}
	public void setUSB_MASS_STORAGE_ENABLED(int uSB_MASS_STORAGE_ENABLED) {
		USB_MASS_STORAGE_ENABLED = uSB_MASS_STORAGE_ENABLED;
	}
	public int getWIFI_NETWORKS_AVAILABLE_NOTIFICATION_ON() {
		return WIFI_NETWORKS_AVAILABLE_NOTIFICATION_ON;
	}
	public void setWIFI_NETWORKS_AVAILABLE_NOTIFICATION_ON(int wIFI_NETWORKS_AVAILABLE_NOTIFICATION_ON) {
		WIFI_NETWORKS_AVAILABLE_NOTIFICATION_ON = wIFI_NETWORKS_AVAILABLE_NOTIFICATION_ON;
	}
	public int getWIFI_ON() {
		return WIFI_ON;
	}
	public void setWIFI_ON(int wIFI_ON) {
		WIFI_ON = wIFI_ON;
	}
	@Override
	public String toString() {
		return "AcraSettingsSecure [ADB_ENABLED=" + ADB_ENABLED + ", ALLOW_MOCK_LOCATION=" + ALLOW_MOCK_LOCATION
				+ ", BLUETOOTH_ON=" + BLUETOOTH_ON + ", DATA_ROAMING=" + DATA_ROAMING + ", DEFAULT_INPUT_METHOD="
				+ DEFAULT_INPUT_METHOD + ", DEVICE_PROVISIONED=" + DEVICE_PROVISIONED + ", ENABLED_INPUT_METHODS="
				+ ENABLED_INPUT_METHODS + ", INSTALL_NON_MARKET_APPS=" + INSTALL_NON_MARKET_APPS
				+ ", LOCATION_PROVIDERS_ALLOWED=" + LOCATION_PROVIDERS_ALLOWED + ", NETWORK_PREFERENCE="
				+ NETWORK_PREFERENCE + ", USB_MASS_STORAGE_ENABLED=" + USB_MASS_STORAGE_ENABLED
				+ ", WIFI_NETWORKS_AVAILABLE_NOTIFICATION_ON=" + WIFI_NETWORKS_AVAILABLE_NOTIFICATION_ON + ", WIFI_ON="
				+ WIFI_ON + "]";
	}
	
}
