package is.ejb.bl.acra;

public class AcraSettingsSystem {
	private int ACCELEROMETER_ROTATION;
	private int AIRPLANE_MODE_ON;
	private String AIRPLANE_MODE_RADIOS;
	private int AUTO_TIME;
	private String DATE_FORMAT;
	private int DIM_SCREEN;
	private String FONT_SCALE;
	private int MODE_RINGER;
	private int MODE_RINGER_STREAMS_AFFECTED;
	private int MUTE_STREAMS_AFFECTED;
	private String NEXT_ALARM_FORMATTED;
	private int SCREEN_BRIGHTNESS;
	private long SCREEN_OFF_TIMEOUT;
	private int STAY_ON_WHILE_PLUGGED_IN;
	private String TRANSITION_ANIMATION_SCALE;
	private int VIBRATE_ON;
	private int VOLUME_ALARM;
	private int VOLUME_MUSIC;
	private int VOLUME_NOTIFICATION;
	private int VOLUME_RING;
	private int VOLUME_SYSTEM;
	private int VOLUME_VOICE;
	private String WINDOW_ANIMATION_SCALE;
	public int getACCELEROMETER_ROTATION() {
		return ACCELEROMETER_ROTATION;
	}
	public void setACCELEROMETER_ROTATION(int aCCELEROMETER_ROTATION) {
		ACCELEROMETER_ROTATION = aCCELEROMETER_ROTATION;
	}
	public int getAIRPLANE_MODE_ON() {
		return AIRPLANE_MODE_ON;
	}
	public void setAIRPLANE_MODE_ON(int aIRPLANE_MODE_ON) {
		AIRPLANE_MODE_ON = aIRPLANE_MODE_ON;
	}
	public String getAIRPLANE_MODE_RADIOS() {
		return AIRPLANE_MODE_RADIOS;
	}
	public void setAIRPLANE_MODE_RADIOS(String aIRPLANE_MODE_RADIOS) {
		AIRPLANE_MODE_RADIOS = aIRPLANE_MODE_RADIOS;
	}
	public int getAUTO_TIME() {
		return AUTO_TIME;
	}
	public void setAUTO_TIME(int aUTO_TIME) {
		AUTO_TIME = aUTO_TIME;
	}
	public String getDATE_FORMAT() {
		return DATE_FORMAT;
	}
	public void setDATE_FORMAT(String dATE_FORMAT) {
		DATE_FORMAT = dATE_FORMAT;
	}
	public int getDIM_SCREEN() {
		return DIM_SCREEN;
	}
	public void setDIM_SCREEN(int dIM_SCREEN) {
		DIM_SCREEN = dIM_SCREEN;
	}
	public String getFONT_SCALE() {
		return FONT_SCALE;
	}
	public void setFONT_SCALE(String fONT_SCALE) {
		FONT_SCALE = fONT_SCALE;
	}
	public int getMODE_RINGER() {
		return MODE_RINGER;
	}
	public void setMODE_RINGER(int mODE_RINGER) {
		MODE_RINGER = mODE_RINGER;
	}
	public int getMODE_RINGER_STREAMS_AFFECTED() {
		return MODE_RINGER_STREAMS_AFFECTED;
	}
	public void setMODE_RINGER_STREAMS_AFFECTED(int mODE_RINGER_STREAMS_AFFECTED) {
		MODE_RINGER_STREAMS_AFFECTED = mODE_RINGER_STREAMS_AFFECTED;
	}
	public int getMUTE_STREAMS_AFFECTED() {
		return MUTE_STREAMS_AFFECTED;
	}
	public void setMUTE_STREAMS_AFFECTED(int mUTE_STREAMS_AFFECTED) {
		MUTE_STREAMS_AFFECTED = mUTE_STREAMS_AFFECTED;
	}
	public String getNEXT_ALARM_FORMATTED() {
		return NEXT_ALARM_FORMATTED;
	}
	public void setNEXT_ALARM_FORMATTED(String nEXT_ALARM_FORMATTED) {
		NEXT_ALARM_FORMATTED = nEXT_ALARM_FORMATTED;
	}
	public int getSCREEN_BRIGHTNESS() {
		return SCREEN_BRIGHTNESS;
	}
	public void setSCREEN_BRIGHTNESS(int sCREEN_BRIGHTNESS) {
		SCREEN_BRIGHTNESS = sCREEN_BRIGHTNESS;
	}
	public long getSCREEN_OFF_TIMEOUT() {
		return SCREEN_OFF_TIMEOUT;
	}
	public void setSCREEN_OFF_TIMEOUT(long sCREEN_OFF_TIMEOUT) {
		SCREEN_OFF_TIMEOUT = sCREEN_OFF_TIMEOUT;
	}
	public int getSTAY_ON_WHILE_PLUGGED_IN() {
		return STAY_ON_WHILE_PLUGGED_IN;
	}
	public void setSTAY_ON_WHILE_PLUGGED_IN(int sTAY_ON_WHILE_PLUGGED_IN) {
		STAY_ON_WHILE_PLUGGED_IN = sTAY_ON_WHILE_PLUGGED_IN;
	}
	public String getTRANSITION_ANIMATION_SCALE() {
		return TRANSITION_ANIMATION_SCALE;
	}
	public void setTRANSITION_ANIMATION_SCALE(String tRANSITION_ANIMATION_SCALE) {
		TRANSITION_ANIMATION_SCALE = tRANSITION_ANIMATION_SCALE;
	}
	public int getVIBRATE_ON() {
		return VIBRATE_ON;
	}
	public void setVIBRATE_ON(int vIBRATE_ON) {
		VIBRATE_ON = vIBRATE_ON;
	}
	public int getVOLUME_ALARM() {
		return VOLUME_ALARM;
	}
	public void setVOLUME_ALARM(int vOLUME_ALARM) {
		VOLUME_ALARM = vOLUME_ALARM;
	}
	public int getVOLUME_MUSIC() {
		return VOLUME_MUSIC;
	}
	public void setVOLUME_MUSIC(int vOLUME_MUSIC) {
		VOLUME_MUSIC = vOLUME_MUSIC;
	}
	public int getVOLUME_NOTIFICATION() {
		return VOLUME_NOTIFICATION;
	}
	public void setVOLUME_NOTIFICATION(int vOLUME_NOTIFICATION) {
		VOLUME_NOTIFICATION = vOLUME_NOTIFICATION;
	}
	public int getVOLUME_RING() {
		return VOLUME_RING;
	}
	public void setVOLUME_RING(int vOLUME_RING) {
		VOLUME_RING = vOLUME_RING;
	}
	public int getVOLUME_SYSTEM() {
		return VOLUME_SYSTEM;
	}
	public void setVOLUME_SYSTEM(int vOLUME_SYSTEM) {
		VOLUME_SYSTEM = vOLUME_SYSTEM;
	}
	public int getVOLUME_VOICE() {
		return VOLUME_VOICE;
	}
	public void setVOLUME_VOICE(int vOLUME_VOICE) {
		VOLUME_VOICE = vOLUME_VOICE;
	}
	public String getWINDOW_ANIMATION_SCALE() {
		return WINDOW_ANIMATION_SCALE;
	}
	public void setWINDOW_ANIMATION_SCALE(String wINDOW_ANIMATION_SCALE) {
		WINDOW_ANIMATION_SCALE = wINDOW_ANIMATION_SCALE;
	}
	@Override
	public String toString() {
		return "AcraSettingsSystem [ACCELEROMETER_ROTATION=" + ACCELEROMETER_ROTATION + ", AIRPLANE_MODE_ON="
				+ AIRPLANE_MODE_ON + ", AIRPLANE_MODE_RADIOS=" + AIRPLANE_MODE_RADIOS + ", AUTO_TIME=" + AUTO_TIME
				+ ", DATE_FORMAT=" + DATE_FORMAT + ", DIM_SCREEN=" + DIM_SCREEN + ", FONT_SCALE=" + FONT_SCALE
				+ ", MODE_RINGER=" + MODE_RINGER + ", MODE_RINGER_STREAMS_AFFECTED=" + MODE_RINGER_STREAMS_AFFECTED
				+ ", MUTE_STREAMS_AFFECTED=" + MUTE_STREAMS_AFFECTED + ", NEXT_ALARM_FORMATTED=" + NEXT_ALARM_FORMATTED
				+ ", SCREEN_BRIGHTNESS=" + SCREEN_BRIGHTNESS + ", SCREEN_OFF_TIMEOUT=" + SCREEN_OFF_TIMEOUT
				+ ", STAY_ON_WHILE_PLUGGED_IN=" + STAY_ON_WHILE_PLUGGED_IN + ", TRANSITION_ANIMATION_SCALE="
				+ TRANSITION_ANIMATION_SCALE + ", VIBRATE_ON=" + VIBRATE_ON + ", VOLUME_ALARM=" + VOLUME_ALARM
				+ ", VOLUME_MUSIC=" + VOLUME_MUSIC + ", VOLUME_NOTIFICATION=" + VOLUME_NOTIFICATION + ", VOLUME_RING="
				+ VOLUME_RING + ", VOLUME_SYSTEM=" + VOLUME_SYSTEM + ", VOLUME_VOICE=" + VOLUME_VOICE
				+ ", WINDOW_ANIMATION_SCALE=" + WINDOW_ANIMATION_SCALE + "]";
	}
	
}
