package is.ejb.bl.business;

public enum UserErrorCategoryEnum {
	NO_CONVERSION,	
	NO_REWARD,
	FAILED_REWARD,
	PROBLEM_NO_VIDEO_REWARD,
	PROBLEM_NO_WALLET_RECHARGE,
	PROBLEM_NO_WALLET_PAYOUT,
	PROBLEM_OFFER_NOT_WORKING,
	PROBLEM_NO_INSTANT_REWARD;
}
