package is.ejb.bl.system.mail;

public enum EmailType {
	REGISTRATION_REWARDZ, 
	REGISTRATION_GOAHEAD,
	REGISTRATION_CINETREATS,
	PASSWORD_CHANGE,
	PASSWORD_RECOVERY,
	REPORTING,
	INVITATION,
	TRIPPA_QUIDCO_REWARD_CASHBACK_SUCCESS,
	TRIPPA_QUIDCO_REWARD_CASHBACK_TRACKED,
	TRIPPA_QUIDCO_REWARD_AVAIBLE_TO_SPEND,
	TRIPPA_QUIDCO_CREDIT_CARD_REGISTRATION,
	SNAPDEAL_OFFER_TRACKED,
	SNAPDEAL_OFFER_CANCELLED,
	SNAPDEAL_OFFER_APPROVED

}
