package is.ejb.bl.timers;

import java.io.Serializable;

public class TimerType {

	public static String TIMER_AFA_SESSION = "TIMER_AFA_SESSION";
	public static String TIMER_QUIDCO_GET_DELTA = "TIMER_QUIDCO_GET_DELTA";
	public static String TIMER_SNAPDEAL_APPROVE_REWARDS = "TIMER_SNAPDEAL_APPROVE_REWARDS";
	public static String TIMER_SNAPDEAL_GET_REPORTS = "TIMER_SNAPDEAL_GET_REPORTS";
	public static String TIMER_SNAPDEAL_GET_OFFERS = "TIMER_SNAPDEAL_GET_OFFERS";
	public static String TIMER_CRF = "TIMER_CRF";
	public static String TIMER_REPORTING = "TIMER_REPORTING";
	public static String TIMER_SYSTEM_MONITORING = "TIMER_SYSTEM_MONITORING";
	public static String TIMER_SQL_DATA_SIZE_MONITORING = "TIMER_SQL_DATA_SIZE_MONITORING";
	public static String TIMER_NETWORK_STATS_HOURLY = "TIMER_NETWORK_STATS_HOURLY";
	public static String TIMER_OFFER_WALL_GENERATION = "TIMER_OFFER_WALL_GENERATION";
	public static String TIMER_ANALYTICS_MAILER_SYSTEM_STATUS = "TIMER_ANALYTICS_MAILER_SYSTEM_STATUS";
	public static String TIMER_SYSTEM_PERFORMANCE_MONITORING = "TIMER_SYSTEM_PERFORMANCE_MONITORING";
	public static String TIMER_SYSTEM_MAINTENANCE_MONITORING = "TIMER_SYSTEM_MAINTENANCE_MONITORING";
	public static String TIMER_ANALYTICS_DEVICE_MONITORING = "TIMER_ANALYTICS_DEVICE_MONITORING";
	public static String TIMER_DEVICE_ALERTS_REPORTING = "TIMER_DEVICE_ALERTS_REPORTING";
	public static String TIMER_ANALYTICS_FORECASTING = "TIMER_ANALYTICS_FORECASTING";

}
